title: Ethnic groups in the 2021 census
description: >-
  Ethnic Groups in the 2021 census
baseurl: "/dem-charts/"
url: "https://mark-solfiac.github.io/dem-charts/"
twitter_username: marksolfiac
github_username:  mark-solfiac

theme: minima

plugins:
- jekyll-remote-theme

