title: Ethnic groups in the 2021 United Kingdom census
description: >-
  Charts of ethnic groups by sex, total numbers and percentages in the 2021 United Kingdom census
baseurl: "/dem-charts/"
url: "https://marksolfiac.github.io/dem-charts/"
twitter_username: marksolfiac
github_username: marksolfiac

theme: minima

plugins:
  - jekyll-remote-theme
