title: Ethnic groups in the 2021 census
email: mark.solfiac.100@gmail.com
description: >-
  Ethnic Groups in the 2021 census
baseurl: "/dem-charts/"
url: "https://mark-solfiac.github.io/dem-charts/"
twitter_username: marksolfiac
github_username:  mark-solfiac
google_analytics: G-54P31TLC7X

theme: minima

plugins:
- jekyll-remote-theme

